config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "users#index"

  get "/auth/:provider/callback", to: "omni_sessions#create"

  resources :products
  resources :users do
    collection do
      get "login", action: :login
      post "login", action: :do_login
      delete "login", action: :logout
    end
  end

  
  get 'sells/index'

  get 'sells/:id', to: 'sells#show'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	# Valida que quantity sea un numero entero
	validates :quantity, numericality: {greater_than: 0}
	# Validacion Personalizada
	validate :validate_stock
	# Pertenece a product y a sell
	belongs_to :product
	belongs_to :sell
	# antes de crear llama al metodo init_value
	before_create :init_value
	# despues de crear actualiza la cantidad de inventario disponible
	after_create :update_stock
	# despues de borrar devuelve el valor al stock de los productos
	after_destroy :add_stock

	def init_value
		self.value = self.quantity * self.product.price 
	end

	def update_stock
		self.product.update_attribute(:quantity, self.product.quantity - self.quantity)
	end

	def validate_stock
		if self.quantity > self.product.quantity
			errors.add(:quantity, "No hay suficientes productos en stock")
		end	
	end	

	def add_stock
		self.product.update_attribute(:quantity, self.product.quantity + self.quantity)
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	# Validaciones para las columnas que conforman la clase Product
	validates :ref, :price, :quantity, :brand, :name, :description, :size, :color, presence: true
	validates :size, length: {in: 1..3}
	validates :price, numericality: {greater_than: 0}
	validates :ref, uniqueness: true

	# Un producto tiene varios items de linea (Puede interpretarse como que un usuario tiene varios items en una factura)
	has_many :line_items
end

app/models/sell.rb
class Sell < ActiveRecord::Base
	# Validaciones
	validates :total, numericality: {greater_or_equal_than: 0}
	validates :comment, :total, presence: {message: "Pilas!! no puede estar vacio!!!"}

	# Una venta tiene varias items de linea. Y cada que se agrega un item de linea a la venta se suman las cantidades
	# y depues de borrar un item de linea se descuenta un item del valor total 
	has_many :line_items, after_add: :add_item, after_remove: :remove_item
	belongs_to :user

	def add_item(line_item)
		if line_item.valid?
			self.update_attribute(:total, 
				self.total + line_item.value)
		end
	end

	def remove_item(line_item)
		if line_item.valid?
			self.update_attribute(:total, 
				self.total - line_item.value)
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, allow_blank: true

  has_many :sells

  #For Carrierwave
  mount_uploader :avatar, AvatarUploader

  after_create :send_email

  def self.create_with_ommiauth(auth)
    self.create! do |user|
    user.provider = auth['provider']
    user.uid = auth['uid']
    user.name = auth['info']['name']
    user.token = auth['credentials']['name']
    user.secret = auth['credentials']['secret']
    user.url_photo = auth['info']['image']
    end
  end 

end

  def login
    User.where(email: self.email, password: self.password).first
  end

  #callback for sending the email
  def send_email
    # RegisterMailer.registration(self).deliver_now
    SendEmailJob.set(wait: 20.seconds).perform_later(self)
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_required
    if session[:user_id].nil?
      redirect_to login_users_path, notice: 'Debes logearte primero'
    end
  end

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end
end

app/controllers/omnisessions_controller.rb
class OmnisessionsController < ApplicationController
	def create
		auth = request.env['omniauth.auth']
		user = User.where(provider: auth['provider'],uid: auth['uid']).first || 
		User.create_with_ommniauth(auth)	
        
  		#Creacion de variable de session
		session[:user_id] = user.id
  		redirect_to root_path
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :login_required
	before_action :products_params, only: [:create]

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(products_params)
    if @product.save
      redirect_to products_path, notice: 'Todo bien!'
    else
      render 'new'
    end  
  end

  private

  def products_params
  	params.require(:product).permit(:ref, :price, :quantity, :brand, :name, :description, :size, :color)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def index
  	@sells = Sell.all
  end

  def show
  	@sell = Sell.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #users/index
  def index
  	@users = User.all
  	#puts "#{@users.inspect}"
  end

  #users/123
  def show
  	@user = User.find(params[:id])
  end

  #users/new
  def new
  	@user = User.new
  end

  #users/
  def create
  	params_filtered = params.require(:user).permit(:name, :email, :password, :avatar)
  	#params_filtered = {name: "michel", email:"michel@gmai.com", password:"2131312"}
  	@user = User.new(params_filtered)
  	if @user.save
  		redirect_to users_path
  	else
  		render 'new'
  	end
  end

  #users/:id
  def update
    params_filtered = params.require(:user).permit(:name, :email, :password)
    #params_filtered = {name: "michel", email:"michel@gmai.com", password:"2131312"}
    @user = User.find(params[:id])
    if @user.update(params_filtered)
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def login
    @user = User.new
  end

  def do_login
    params_filtered = params.require(:user).permit(:email, :password)
    @user = User.new(params_filtered)
    if @user_logged = @user.login
      session[:user_id] = @user_logged.id
      redirect_to products_path, notice: "Bienvenido #{@user.name}"
    else
      flash[:error] = 'Ocurrio un error logeando al usuario'
      render 'login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omnisessions_helper.rb
module OmnisessionsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PruebaClass</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<%if current_user%>
    <span><%= current_user.name%></span>
    <%= image_tag current_user.url_photo%>
<%else%>
<%= link_to 'Ingresa con Twitter', '/auth/twitter'%>
<%end%>

<div class="container-fluid">
    <header class="row">
        <div class="col-md-6">
            <p class="notice"><%= notice %></p>

            <p class="alert"><%= alert %></p>
        </div>
        <p class="navbar-text pull-right">
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile: '+ current_user.name, edit_user_registration_path, :class => 'navbar-link' %>
                |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
        </p>
    </header>
    <section id="main" class="col-md-8 col-md-offset-2">
        <%= yield %>
    </section>
    <footer>
    </footer>
</div>
</body>
</html>

app/views/products/index.html.erb
<h1>Listando productos</h1>

<%= link_to 'Nuevo producto', new_product_path, class: 'btn btn-primary' %>
<div class="table-responsive">
  <table class="table table-bordered table-striped table-hover">
    <tr>
      <th>Reference</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Brand</th>
      <th>Name</th>
      <th>Description</th>
      <th>Size</th>
      <th>Color</th>
    </tr>
    <tr>
      <% @products.each do |product| %>
          <td><%= product.ref %></td>
          <td><%= product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.brand %></td>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.size %></td>
          <td><%= product.color %></td>
          <td><%= link_to 'Ver producto...', product_path(product) %></td>
      <% end %>
    </tr>
  </table>
</div>

app/views/products/new.html.erb
<h1>Crear un nuevo Poducto</h1>

<%= form_for @product, html: { class: 'form-horizontal' } do |f| %>
    <div class="form-group">
      <%= f.label :ref %>
      <%= f.text_field :ref %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <div class="form-group">
      <%= f.label :quantity %>
      <%= f.select :quantity, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9]) %></br>
    </div>
    <div class="form-group">
      <%= f.label :brand %>
      <div class="radio-inline">
        <%= f.radio_button(:brand, "Totto") %>Toto
      </div>
      <div class="radio-inline">
        <%= f.radio_button(:brand, "Americanino") %>Americanino
      </div>
      <div class="radio-inline">
        <%= f.radio_button(:brand, "jean") %>Jean
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="form-group">
      <%= f.label :size %>
      <%= f.text_field :size %>
    </div>
    <div class="form-group">
      <%= f.label :color %>
      <%= f.select :color, options_for_select(["red", "blue", "gold"]) %>
    </div>
    <%= f.submit "Guardar", class: 'btn btn-primary' %>
<% end %>

app/views/products/show.html.erb
<h1>Detalle del producto</h1>

<h4>Ref:</h4><%= @product.ref%> 
<br/>
<h4>Price:</h4> <%= @product.price%>
<br/>
<h4>Quantity:</h4> <%= @product.quantity%>
<br/>
<h4>Brand:</h4> <%= @product.brand%>
<br/>
<h4>Name:</h4> <%= @product.name%>
<br/>
<h4>Description:</h4> <%= @product.description%>
<br/>
<h4>Size:</h4> <%= @product.size%>
<br/>
<h4>Color</h4> <%= @product.color%>
<br/>

<%= link_to 'Volver al listado', url_for(controller: :products, action: :index) %>


			
			
			
			
			
			
			
			

app/views/sells/index.html.erb
<h1>Lista de ventas</h1>

<table>
	<tr>
		<th>Numero venta | </th> 
		<th>Nombre del usuario |</th>
		<th>Email del usuario |</th>
		<th>Producto |</th>
		<th>Creada en |</th>
		<th>Acciones |</th>
	</tr>
	<% @sells.each do |sell| %>
		<tr>
			<td><%= sell.id%> </td>
			<td><%= sell.user.name.capitalize %> </td>
			<td><%= sell.user.email %> </td>
			<td><%= sell.created_at%> </td>
			<td><%= link_to 'Ver detalle', url_for(controller: :sells, action: :show, id: sell.id) %></td>
		</tr>
	<% end %>
</table>

app/views/sells/show.html.erb
<h1>Detalle del usuario</h1>

<h2>Nombre:</h2> <%= @sell.line_item.quantity %> 
<br/>
<h2>Email:</h2> <%= @sell.line_item.product.value %> 
<br/><br/>

<%= link_to 'Volver al listado', url_for(controller: :users, action: :index) %>

app/views/users/index.html.erb
<h1>Lista de usuarios</h1>

<table>
	<tr>
		<th>Nombre del usuario</th>
		<th>Email</th>
		<th>Acciones</th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= link_to 'Ver detalle', url_for(controller: :users, action: :show, id: user.id) %></td>
		</tr>
	<% end %>
</table>

app/views/users/login.html.erb
<% if notice %>
    <%= notice %>
<% end %>

<fieldset>
  <legend>Inicio de sesión</legend>

  <%= form_for @user, url: { action: :login }, method: :post, html: { class: 'form-horizontal' } do |f| %>
      <div class="form-group">
        <%= f.label :email, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :email, class: 'form-control', placeholder: 'email' %>
        </div>
      </div>
      <br>

      <div class="form-group">
        <%= f.label :password, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
        </div>
      </div>
      <br>
      <% if flash[:error] %>
          <div class="errors">
            <%= flash[:error] %>
          </div>
      <% end %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Login', class: 'btn btn-primary' %>
        </div>
      </div>
  <% end %>

</fieldset>

app/views/users/new.html.erb
<% if !@user.errors.empty? %>
	<ol>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ol>
<% end %>

<%= form_for @user do |f| %>
	<%= f.label 'Nombre' %><br/>
	<%= f.text_field :name %><br/>
	<%= f.label 'Correo' %><br/>
	<%= f.text_field :email %><br/>
	<%= f.label 'Contraseña' %><br/>
	<%= f.text_field :password %><br/>
	<%= f.submit %><br/><br/>
	<%= f.label 'Avatar' %><br/>
	<%= f.file_field :avatar %><br/>
<% end %>

app/views/users/show.html.erb
<h1>Detalle del usuario</h1>

<h2>Nombre:</h2> <%= @user.name %> 
<br/>
<h2>Email:</h2> <%= @user.email %> 
<br/><br/>
<h2>Avatar:</h2> <%= image_tag @user.avatar.url %> 
<br/><br/>

<%= link_to 'Volver al listado', url_for(controller: :users, action: :index) %>